// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteURLExpired(ctx context.Context) error
	GetUrlByShortCode(ctx context.Context, shortCode string) (Url, error)
	IsShortCodeAvailable(ctx context.Context, shortCode string) (bool, error)
}

var _ Querier = (*Queries)(nil)
